services:
  postgres:
    image: postgres:16
    container_name: vyzov_postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: vyzov_backend
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: vyzov_frontend
    env_file: .env
    depends_on:
      - backend
    expose:
      - "3000"

  nginx:
    image: nginx:1.25-alpine
    container_name: vyzov_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data: